# backend/Dockerfile
# Use an official Node runtime as the base image
FROM node:20-alpine

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle the app source inside the Docker image
COPY . .

# Run the setup script
# RUN ["npm", "run", "setup"]
# RUN npm run reset
# RUN npm run setup

# Make port 8888 available to the outside world
EXPOSE 8888

# Run the app when the container launches
CMD ["npm", "run", "start"]