# name: createimages

# on:
#   push:
#     branches: master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Install buildx
#         id: buildx
#         uses: crazy-max/ghaction-docker-buildx@v1
#         with:
#           version: latest
#       - name: Login to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#       - name: Build and push frontend image
#         run: |
#             cd frontend
#             docker buildx build --push \
#                 --tag srcoloma/crm-frontend:latest \
#                 --platform linux/amd64,linux/arm/v7 .  
#       - name: Build and push backend image
#         run: |
#             cd backend
#             docker buildx build --push \
#                 --tag srcoloma/crm-backend:latest \
#                 --platform linux/amd64,linux/arm/v7 .



name: createimages

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build front and push
        uses: docker/build-push-action@v5
        with:
            context: ./frontend
            platforms: linux/amd64,linux/arm64
            push: true
            tags: srcoloma/crm-frontend:latest
      - name: Build back and push
        uses: docker/build-push-action@v5
        with:
            context: ./backend
            platforms: linux/amd64,linux/arm64
            push: true
            tags: srcoloma/crm-backend:latest