name: createimages

on:
  push:
    branches: estable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push frontend image
        run: |
            cd frontend
            docker buildx build --push \
                --tag srcoloma/crm-frontend:latest \
                --platform linux/amd64,linux/arm/v7 .  
      - name: Build and push backend image
        run: |
            cd backend
            docker buildx build --push \
                --tag srcoloma/crm-backend:latest \
                --platform linux/amd64,linux/arm/v7 .